name: "action-comment-pull-request"
description: "Comment a pull request with the provided message"
inputs:
  message:
    description: 'Message that should by displayed inside the pull request'
    required: true
  GITHUB_TOKEN:
    description: 'Github token of the repository'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.message }}
    - ${{ inputs.GITHUB_TOKEN }}
